kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-api-deployment
spec:
  selector:
    matchLabels:
      app: my-api-deployment
  template:
    metadata:
      labels:
        app: my-api-deployment
    spec:
      containers:
      - name: my-api-deployment
        image: lucassimao/my-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: IS_PROD
          value: "true"
        - name: PORT
          value: "9000"
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-secret-credentials
              key: POSTGRES_DB
        - name: DATABASE_HOST
          value: postgresdb
        - name: DATABASE_PORT
          value: "5432"
        ports:
        - containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: my-api-service
spec:
  selector:
    app: my-api-deployment
  type: LoadBalancer
  ports:
  - name: http-api
    protocol: TCP
    port: 9000
    targetPort: 9000
